//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareLife {
    
    public partial class ContactDonor {
        
        protected global::System.Web.UI.WebControls.Panel pnlNotLoggedIn;
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlContact;
        protected global::System.Web.UI.WebControls.Literal litDonorInitial;
        protected global::System.Web.UI.WebControls.Literal litDonorName;
        protected global::System.Web.UI.WebControls.Literal litDonorCity;
        protected global::System.Web.UI.WebControls.Literal litDonorAge;
        protected global::System.Web.UI.WebControls.Literal litDonorBloodGroup;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.TextBox txtSubject;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSubject;
        protected global::System.Web.UI.WebControls.TextBox txtMessage;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMessage;
        protected global::System.Web.UI.WebControls.Button btnSend;
        protected global::System.Web.UI.WebControls.Panel pnlHistory;
        protected global::System.Web.UI.WebControls.Repeater rptMessages;
        protected global::System.Web.UI.WebControls.Panel pnlNotFoundPanel;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkViewInbox;

    }
}
