//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareLife {
    
    public partial class DonorMessages {
        
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Literal litInitial;
        protected global::System.Web.UI.WebControls.Literal litName;
        protected global::System.Web.UI.WebControls.Literal litCity;
        protected global::System.Web.UI.WebControls.Literal litAge;
        protected global::System.Web.UI.WebControls.Literal litMobile;
        protected global::System.Web.UI.WebControls.Literal litBloodGroup;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkSendMsgHeader;
        protected global::System.Web.UI.WebControls.Literal litDonorId;
        protected global::System.Web.UI.WebControls.Panel pnlCount;
        protected global::System.Web.UI.WebControls.Literal litCount;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkSendMsgEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlMessages;
        protected global::System.Web.UI.WebControls.Repeater rptMessages;
    }
}
