//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareLife {
    
    public partial class EditDonor {
        
        protected global::System.Web.UI.WebControls.Panel pnlNotLoggedIn;
        protected global::System.Web.UI.WebControls.Literal litDonorIDHeader;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlEditForm;
        protected global::System.Web.UI.WebControls.HiddenField hfDonorID;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGender;
        protected global::System.Web.UI.WebControls.TextBox txtAge;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAge;
        protected global::System.Web.UI.WebControls.RangeValidator rvAge;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected global::System.Web.UI.WebControls.TextBox txtMobile;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMobile;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revMobile;
        protected global::System.Web.UI.WebControls.TextBox txtCity;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCity;
        protected global::System.Web.UI.WebControls.DropDownList ddlBloodGroup;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvBloodGroup;
        protected global::System.Web.UI.WebControls.TextBox txtWeight;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvWeight;
        protected global::System.Web.UI.WebControls.RangeValidator rvWeight;
        protected global::System.Web.UI.WebControls.TextBox txtLastDonationDate;
        protected global::System.Web.UI.WebControls.TextBox txtMedicalConditions;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
    }
}
