//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareLife {
    
    public partial class Search {
        
        protected global::System.Web.UI.WebControls.DropDownList ddlSearchBloodGroup;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Label lblSearchResult;
        protected global::System.Web.UI.WebControls.GridView gvSearchDonors;
    }
}
